name: CI Build

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    steps:
      - name: Setup LLVM Paths
        if: runner.os == 'Windows'
        run: | 
          echo 'C:\msys64\mingw32\bin' >> $GITHUB_PATH
          echo 'LIBCLANG_PATH=C:\msys64\mingw32\bin' >> $GITHUB_ENV
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cargo Build 
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --workspace
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --workspace

