name: CI Build

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]


    steps:
      - name: Find libclang.dll
        run: |
          Get-Childitem –Path C:\msys64\ -Include *clang.dll* -File -Recurse -ErrorAction SilentlyContinue
